from plots_functions.acumulated_jobs_cpu_gpu import AccumulatedJobsCPUvsGPU
from plots_functions.acumulated_jobs import AccumulatedJobs
from plots_functions.avg_req_cpu_gpu import AvgReqCpuGpu
from plots_functions.jobs_cpu_gpu_by_month import CpuGpuJobsByMonth
from plots_functions.jobs_executions_by_month import JobsExecutionsByMonth
from plots_functions.gpus_memory import GpusMemory
from plots_functions.acum_user_growth import CumulativeUserGrowth
from plots_functions.users_subsc_by_month import UserSubscByMonth
from plots_functions.utilization import Utilization

AccumulatedJobsCPUvsGPU()
AccumulatedJobs()
AvgReqCpuGpu()
CpuGpuJobsByMonth()
JobsExecutionsByMonth()
GpusMemory()
CumulativeUserGrowth()
UserSubscByMonth()
Utilization()
